#!/usr/bin/env bash
echo "Running detekt check..."
OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew ktlintFormat detekt > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "****************************************"
  echo "              Detekt failed             "
  echo " Fix the above issues before committing "
  echo "****************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT